'use client';

import Link from 'next/link';
import {
  ArrowRight,
  Sparkles,
  Search,
  GitBranch,
  Zap,
  Download,
  Plus,
  Archive,
} from 'lucide-react';
import { useTranslation } from '@/i18n/client';
import { useSkills } from '@/hooks/use-skills';
import { useAgentPresets } from '@/hooks/use-agents';
import { useMCPServers } from '@/hooks/use-mcp';
import { useExecutors } from '@/hooks/use-executors';

function StatCard({ value, label, href, isLoading }: { value: number; label: string; href: string; isLoading: boolean }) {
  return (
    <Link href={href} className="glass-card rounded-lg p-4 transition-[background-color] hover:bg-accent/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
      {isLoading ? (
        <div className="h-8 w-12 animate-pulse rounded bg-muted" />
      ) : (
        <div className="text-2xl font-bold tabular-nums">{value}</div>
      )}
      <div className="mt-1 text-sm text-muted-foreground">{label}</div>
    </Link>
  );
}

const QUICK_ACTIONS = [
  { href: '/skills/find', icon: Search, titleKey: 'quickActions.findSkills.title', descKey: 'quickActions.findSkills.description', accent: 'from-blue-500 to-cyan-500' },
  { href: '/skills/new', icon: Plus, titleKey: 'quickActions.createSkill.title', descKey: 'quickActions.createSkill.description', accent: 'from-violet-500 to-purple-500' },
  { href: '/import', icon: Download, titleKey: 'quickActions.importSkill.title', descKey: 'quickActions.importSkill.description', accent: 'from-emerald-500 to-teal-500' },
  { href: '/skills/evolve', icon: Zap, titleKey: 'quickActions.evolveSkills.title', descKey: 'quickActions.evolveSkills.description', accent: 'from-amber-500 to-orange-500' },
] as const;

const FEATURES = [
  { icon: Sparkles, titleKey: 'featureCards.conversational.title', descKey: 'featureCards.conversational.description', bg: 'bg-blue-500/10 dark:bg-blue-400/10', color: 'text-blue-600 dark:text-blue-400' },
  { icon: GitBranch, titleKey: 'featureCards.autoGenerated.title', descKey: 'featureCards.autoGenerated.description', bg: 'bg-violet-500/10 dark:bg-violet-400/10', color: 'text-violet-600 dark:text-violet-400' },
  { icon: Zap, titleKey: 'featureCards.evolution.title', descKey: 'featureCards.evolution.description', bg: 'bg-amber-500/10 dark:bg-amber-400/10', color: 'text-amber-600 dark:text-amber-400' },
  { icon: Archive, titleKey: 'featureCards.backup.title', descKey: 'featureCards.backup.description', bg: 'bg-emerald-500/10 dark:bg-emerald-400/10', color: 'text-emerald-600 dark:text-emerald-400' },
] as const;

export default function Home() {
  const { t } = useTranslation('home');

  const { data: skillsData, isLoading: skillsLoading } = useSkills();
  const { data: agentsData, isLoading: agentsLoading } = useAgentPresets();
  const { data: mcpData, isLoading: mcpLoading } = useMCPServers();
  const { data: executorsData, isLoading: executorsLoading } = useExecutors();

  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        {/* Hero */}
        <section className="relative overflow-hidden">
          {/* Animated gradient background (decorative, uses transform for GPU compositing) */}
          <div
            aria-hidden="true"
            className="absolute inset-y-0 -left-1/2 w-[200%] animate-gradient-shift motion-reduce:animate-none opacity-[0.07] dark:opacity-[0.12]"
            style={{ backgroundImage: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 33%, #6366f1 66%, #3b82f6 100%)' }}
          />
          {/* Dot grid overlay (decorative) */}
          <div aria-hidden="true" className="absolute inset-0 dot-grid" />

          <div className="relative container px-4 pt-12 pb-8 md:pt-16 md:pb-10">
            <div className="mx-auto max-w-3xl">
              <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl leading-[1.15] [text-wrap:balance]">
                {t('title')}
              </h1>
              <p className="mt-4 text-lg text-muted-foreground sm:text-xl [text-wrap:balance]">
                {t('tagline')}
              </p>
              <div className="mt-8 inline-flex flex-col items-center gap-1">
                <Link
                  href="/agents/new"
                  className="inline-flex items-center justify-center rounded-lg bg-gradient-to-r from-blue-600 to-violet-600 dark:from-blue-500 dark:to-violet-500 px-8 py-3.5 text-base font-semibold text-white shadow-md shadow-blue-500/20 transition-[transform,box-shadow] hover:shadow-lg hover:shadow-violet-500/30 hover:scale-[1.02] motion-reduce:transform-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                >
                  {t('cta.main')} <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
                <span className="text-sm text-muted-foreground">
                  {t('cta.subtext')}
                </span>
              </div>
            </div>
          </div>
        </section>

        {/* Stats */}
        <section className="container px-4 pb-8">
          <div className="mx-auto max-w-3xl">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <StatCard value={skillsData?.total ?? 0} label={t('stats.skills')} href="/skills" isLoading={skillsLoading} />
              <StatCard value={agentsData?.total ?? 0} label={t('stats.agents')} href="/agents" isLoading={agentsLoading} />
              <StatCard value={mcpData?.count ?? 0} label={t('stats.mcpServers')} href="/mcp" isLoading={mcpLoading} />
              <StatCard value={executorsData?.total ?? 0} label={t('stats.executors')} href="/executors" isLoading={executorsLoading} />
            </div>
          </div>
        </section>

        {/* Quick Actions */}
        <section className="container px-4 pb-10">
          <div className="mx-auto max-w-3xl">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {QUICK_ACTIONS.map(({ href, icon: Icon, titleKey, descKey, accent }) => (
                <Link
                  key={href}
                  href={href}
                  className="group relative flex items-start gap-3 rounded-lg border p-4 transition-[background-color,border-color] duration-200 hover:bg-accent/50 hover:border-border/80 overflow-hidden focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                >
                  {/* Gradient left accent on hover */}
                  <div className={`absolute left-0 top-0 bottom-0 w-[3px] bg-gradient-to-b ${accent} opacity-0 group-hover:opacity-100 transition-opacity duration-200`} />
                  <Icon className="mt-0.5 h-5 w-5 shrink-0 text-muted-foreground group-hover:text-foreground transition-colors" />
                  <div>
                    <div className="font-medium">{t(titleKey)}</div>
                    <div className="text-sm text-muted-foreground">{t(descKey)}</div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="container px-4 py-16 border-t">
          <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4">
            {FEATURES.map(({ icon: Icon, titleKey, descKey, bg, color }, i) => (
              <div
                key={titleKey}
                className="fade-in-up flex flex-col gap-3"
                style={{ '--delay': `${i * 100}ms` } as React.CSSProperties}
              >
                <div className="flex items-center gap-2.5">
                  <div className={`flex h-8 w-8 items-center justify-center rounded-md ${bg}`}>
                    <Icon className={`h-[18px] w-[18px] ${color}`} />
                  </div>
                  <h3 className="font-semibold">{t(titleKey)}</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {t(descKey)}
                </p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
